# Generated by Django 5.0.2 on 2024-02-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группа', 'verbose_name_plural': 'группы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'студент', 'verbose_name_plural': 'студенты'},
        ),
        migrations.AlterField(
            model_name='student',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='отчество'),
        ),
    ]
