# Generated by Django 5.0.2 on 2024-02-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_student_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='EduGroup',
        ),
    ]
